"""Build the plugin's per-template colour guide from the pin generator's colour map.

    python3 scripts/build-template-colors.py ../pin-generator-tool

Reads <pin-generator-tool>/docs/TEMPLATE_COLOR_ROLES.md (generated there by `npm run colors:doc`
from web/src/lib/constants/templateColorPairs.ts) and writes
plugins/insightpins/skills/create-pin/references/template-colors.md. Run it again whenever the
colour map or the palettes change; tests/test_plugin.py checks the result covers every template.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "plugins", "insightpins", "skills", "create-pin", "references",
                   "template-colors.md")

ALL = ["ocean-breeze", "midnight", "lavender", "forest-calm", "cool-mint", "sage", "electric",
       "sunset-glow", "terracotta", "coral-reef", "berry-blush", "rose-gold", "dusty-rose",
       "warm-earth", "minimalist"]
LARGE = ("Title", "Subtitle", "Button")  # 24px and up at default size: 3:1 is enough


def palettes(cell):
    """'9/15: Ocean Breeze, Midnight' -> ids; '15/15: all' -> all; '0/15: none' or '-' -> []."""
    cell = cell.strip()
    if cell in ("-", "") or cell.endswith(": none"):
        return []
    names = cell.split(":", 1)[1].strip()
    if names == "all":
        return list(ALL)
    ids = [n.strip().lower().replace(" ", "-") for n in names.split(",")]
    unknown = [i for i in ids if i not in ALL]
    if unknown:
        sys.exit(f"unknown palette(s) {unknown} in: {cell}")
    return ids


def parse(doc):
    table = doc.split("## Every template", 1)[1]
    rows, current = {}, None
    for line in table.splitlines():
        if not line.startswith("|") or line.startswith("|---") or line.startswith("| Template"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) != 7:
            sys.exit(f"unexpected row: {line}")
        name, role, text, surface, _lowest, at3, at45 = cells
        if name:
            current = name.strip("`")
            rows[current] = []
        rows[current].append({"role": role, "text": text, "surface": surface,
                              "at3": palettes(at3), "at45": palettes(at45)})
    return rows


def describe(template, roles):
    readable = set(ALL)
    no_button = set(ALL)
    notes = []
    for r in roles:
        on_photo = r["surface"] == "the photo"
        if r["role"] in LARGE:
            if on_photo:
                notes.append(f"{r['role'].lower()} sits on the photo: pick a calm, darker area "
                             f"with `image_focus`")
                continue
            if r["role"] == "Subtitle" and r["text"].startswith("`secondary`"):
                notes.append("subtitle is drawn in the light secondary colour and is never "
                             "readable: leave it out (`show_description: false`)")
                continue
            readable &= set(r["at3"])
            if r["role"] != "Button":
                no_button &= set(r["at3"])
    for r in roles:
        if r["role"] == "Label" and r["text"].startswith("`secondary`"):
            notes.append("its label is drawn in the light secondary colour (faint)")
    for r in roles:
        if r["role"] == "Site name" and r["surface"] != "the photo":
            good = [p for p in ALL if p in r["at45"]]
            if not good:
                notes.append("site name is faint on every palette (a small brand line; acceptable)")
            elif len(good) < len(ALL):
                notes.append("site name fully readable only on " + ", ".join(good))
    ordered = [p for p in ALL if p in readable]
    extra = [p for p in ALL if p in no_button and p not in readable]
    return ordered, extra, notes


def build(doc):
    """The text of template-colors.md for the TEMPLATE_COLOR_ROLES.md text `doc`."""
    rows = parse(doc)
    lines = [
        "# Readable palettes for each template",
        "",
        "GENERATED by `scripts/build-template-colors.py` from the pin generator's",
        "`docs/TEMPLATE_COLOR_ROLES.md`. Do not edit by hand.",
        "",
        "\"Readable with\" lists the palettes on which the template's title, subtitle and button all",
        "reach a 3:1 contrast ratio (enough for text of 24px and up): the same list `list_templates`",
        "gives as `readable_palettes`, which comes first when the server sends it. \"Also without a",
        "button\" lists the palettes that become readable when you hide the button (`show_cta: false`).",
        "The notes cover what the server doesn't judge: the site name, labels and text drawn on the",
        "photo, which depends on the photo. Pick the palette from these lists first, then by mood",
        "(`style-selection.md`).",
        "",
        "| Template | Readable with | Also without a button | Notes |",
        "| - | - | - | - |",
    ]
    for template in rows:
        ok, extra, notes = describe(template, rows[template])
        readable = "all 15 palettes" if ok == ALL else (", ".join(ok) if ok else "none")
        lines.append(f"| `{template}` | {readable} | {', '.join(extra)} | "
                     f"{'; '.join(notes)} |")
    return "\n".join(lines) + "\n", len(rows)


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: build-template-colors.py <path to pin-generator-tool repo>")
    with open(os.path.join(sys.argv[1], "docs", "TEMPLATE_COLOR_ROLES.md"), encoding="utf-8") as f:
        text, count = build(f.read())
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"{count} templates written to {os.path.relpath(OUT)}")


if __name__ == "__main__":
    main()
